### ISSUE TITLE
More documentation after installing Amazon2

### ISSUE THREAD

**Issue by rizary** [yosukes-dev/AmazonWSL#11] opened 2020-12-14 00:25 UTC
I try to run the command after installing that mentioned in `README.md`. 

When I run `.\Amazon2.exe config  --default-user rizary`, I got the following error:

```
ERROR
HRESULT:0x80004005
Press any key to continue...
```

It's a fresh install. Do I need to run it as root first and then adding the user there? Or users are automatically added like any other WSL2 distro?

**Comment by yosukes-dev** [comment] 2020-12-14 23:28
After installation, when you run `id`, you get the following output.
```sh
-bash-4.2# id
uid=0(root) gid=0(root) groups=0(root)
```
and when you run `cat /etc/passwd`
```
-bash-4.2# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
polkitd:x:999:998:User for polkitd:/:/sbin/nologin
```

As you can see from the above, the default user is root, and you need to add your own user.
These are basic parts of using Linux, and I don't think they are within the scope of what this repository covers.

**Comment by yosukes-dev** [comment] 2021-11-15 10:35
Duplicate of #14

**Closed as completed by yosukes-dev** 2021-11-15 10:35 UTC
